[project]
authors = ["Matthew Tofano <matttofano2@gmail.com>"]
channels = ["conda-forge"]
name = "en-625-638-group-project"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9.15,<3.10"
numpy = ">=1.19.5,<2"
polars = ">=1.33.1,<2"
pandas = ">=1.4.4,<2"
pillow = ">=9.4.0,<10"
tensorflow = ">=2.6.2,<3"
ipython = ">=8.18.1,<9"
